; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.mcu = esp32
board_build.f_cpu = 240000000L

[env:esp32-COC238]
platform = espressif32
board = esp32ota-devkit-v1
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.31.115
upload_flags =
    --port=3232
    --auth=admin

[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L
